config/routes.rb
Rails.application.routes.draw do
  root to: 'users#sign_in'
  get 'log-in', to: 'session#log_in'
  get 'log-out', to: 'session#log_out'
  resources :followings
  resources :users
  resources :ideas, only: [:create, :index, :show, :new]
  get '/recovery', to: 'users#recovery'
  get '/username', to: 'users#_get_username'
  delete '/unfollow', to: 'followings#unfollow'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/following.rb
class Following < ApplicationRecord
  validates_uniqueness_of :follower_id, scope: [:followed_id]

  belongs_to :follower, class_name: 'User', optional: true
  belongs_to :following, class_name: 'User', optional: true
end

app/controllers/followings_controller.rb
# rubocop:disable Style/IdenticalConditionalBranches,
class FollowingsController < ApplicationController
  before_action :set_following, only: %i[show edit update destroy]

  # GET /followings or /followings.json
  def index
    @followings = Following.all
  end

  # GET /followings/1 or /followings/1.json
  def show; end

  # GET /followings/new
  def new
    @following = Following.new
  end

  # GET /followings/1/edit
  def edit; end

  def check_reverse_pair(followed_id, follower_id)
    Following.where(followed_id: follower_id, follower_id: followed_id)
  end

  # POST /followings or /followings.json
  def create
    @sender = User.find(params[:follower_id])
    reverse_pair = check_reverse_pair(params[:followed_id], params[:follower_id])
    if reverse_pair.empty?
      @follow = Following.new(followed_id: params[:followed_id], follower_id: params[:follower_id])

      if @follow.save
        redirect_to user_path(id: params[:followed_id]), notice: 'Now following'
      else
        redirect_to user_path(id: params[:followed_id]), notice: 'You already followed each other'
      end
    else
      redirect_to user_path(id: params[:followed_id]), notice: 'User either follows you or you followed the user'
    end
  end

  # DELETE /followings/1 or /followings/1.json
  def destroy
    @following.destroy
    respond_to do |format|
      format.html { redirect_to followings_url, notice: 'Following was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def unfollow
    reverse_pair = check_reverse_pair(params[:followed_id], params[:follower_id])
    if reverse_pair.empty?
      @follow = Following.where(followed_id: params[:followed_id], follower_id: params[:follower_id])
      @follow.destroy_all
      redirect_to user_path(id: params[:followed_id]), notice: 'User unfollowed'
    else
      reverse_pair.destroy_all
      redirect_to user_path(id: params[:followed_id]), notice: 'User unfollowed'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_following
    @following = Following.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def following_params
    params.require(:following).permit(:follower_id, :followed_id)
  end
end
# rubocop:enable Style/IdenticalConditionalBranches,

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= form_with(model: following) do |form| %>
  <% if following.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(following.errors.count, "error") %> prohibited this following from being saved:</h2>

      <ul>
        <% following.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :follower_id_id %>
    <%= form.text_field :follower_id_id %>
  </div>

  <div class="field">
    <%= form.label :followed_id_id %>
    <%= form.text_field :followed_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/followings/edit.html.erb
<h1>Editing Following</h1>

<%= render 'form', following: @following %>

<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Followings</h1>

<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Followed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followings.each do |following| %>
      <tr>
        <td><%= following.follower_id_id %></td>
        <td><%= following.followed_id_id %></td>
        <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Following', new_following_path %>

app/views/followings/new.html.erb
<h1>New Following</h1>

<%= render 'form', following: @following %>

<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @following.follower_id_id %>
</p>

<p>
  <strong>Followed:</strong>
  <%= @following.followed_id_id %>
</p>

<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>