config/routes.rb
Rails.application.routes.draw do
  root to: 'users#sign_in'
  get 'log-in', to: 'session#log_in'
  get 'log-out', to: 'session#log_out'
  resources :followings
  resources :users
  resources :ideas, only: [:create, :index, :show, :new]
  get '/recovery', to: 'users#recovery'
  get '/username', to: 'users#_get_username'
  delete '/unfollow', to: 'followings#unfollow'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas, foreign_key: :author_id
  has_many :following
  has_many :followers, class_name: 'Following', dependent: :destroy, foreign_key: :follower_id
  has_many :followings, class_name: 'Following', dependent: :destroy, foreign_key: :followed_id
  has_many :shared_ideas, class_name: 'Idea', dependent: :destroy, foreign_key: :author_id

  validates :username, presence: true, length: { minimum: 3, maximum: 10 }
  validates :email, presence: true, length: { minimum: 3, maximum: 30 }
  validates :fullname, presence: true, length: { minimum: 3, maximum: 30 }
  validates_uniqueness_of :username
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :authorized, only: %i[new create]

  # before_action :require_login, only: %i[index show]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @idea = @user.ideas
  end

  def follow_users; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  # def edit
  # end

  def sign_in; end

  def recovery; end

  def _get_username
    @user = User.find_by(email: params[:email])
    if @user
      flash[:alert] = @user.username
      redirect_to recovery_path
      return
    end
    flash[:alert] = 'User not found'
    redirect_to recovery_path
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        session[:user_name] = @user.fullname
        format.html { redirect_to ideas_path, notice: 'Welcome! You have signed up successfully.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :fullname, :photo, :cover_image, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def destroy
    session.delete(:current_user_id)
  end
end

app/views/users/_form.html.erb
<div class="container col-md-4 col-md-offset-4">
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-3">
    <%= form.label :username %>
    <%= form.text_field :username, class: 'form-control d-block', autofocus: true,  placeholder: 'Username' %>
  </div>

  <div class="m-3">
    <%= form.label :fullname %>
    <%= form.text_field :fullname, class: 'form-control d-block', autofocus: true,  placeholder: 'Fullname' %>
  </div>

  <div class="field m-3">
    <%= form.label :photo %>
    <%= form.text_field :photo, class: 'form-control d-block', autofocus: true,  placeholder: 'Please use an image link' %>
  </div>

  <div class="field m-3">
    <%= form.label :cover_image %>
    <%= form.text_field :cover_image,class: 'form-control d-block', autofocus: true,  placeholder: 'Please use an image link' %>
  </div>

  <div class="field m-3">
    <%= form.label :email %>
    <%= form.text_field :email,class: 'form-control d-block', autofocus: true,  placeholder: 'Email' %>
  </div>

  <div class='m-3'>
    <%= link_to 'Have an account? Please log in', root_path %><br/>
    <%= form.submit 'Register', :class => 'btn btn-default btn-lg btn-submit btn-primary my-2' %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="content">
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Fullname</th>
      <th>Photo</th>
      <th>Cover image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.fullname %></td>
        <td><%= user.photo %></td>
        <td><%= user.cover_image %></td>
        <td><%= link_to 'Show', user %></td>
        <%# <td><%= link_to 'Edit', edit_user_path(user) ></td> %>
        <%# <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } ></td> %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<div>

app/views/users/new.html.erb
<span class="text-center" style="color:red"><%= alert %></span>
<h1 class="page_title text-center m-2">Sign Up</h1>

<%= render 'form', user: @user %>

app/views/users/recovery.html.erb
<h1 class="page_title text-center m-2">Recover your username</h1>
<div class="container col-md-4 col-md-offset-4">
<% if session[:current_user_id] %>
    <% destroy %>
<% end %>
<div class='mt-4'>
<h2 class="text-center" style="color:red"><%= alert %></h2>
<%= form_tag username_path, method: :get do%>
    
    <%= label_tag  "Enter your email address"%>
   <%= text_field_tag :email, params[:email], class: 'form-control d-block', autofocus: true,  placeholder: 'Username'%>
   <small id="emailHelp" class="form-text text-muted">
   <%= link_to 'Click here to log in', root_path	, style: "color: white", class: "form-text text-muted"%>
    </small>
    <%= submit_tag "Submit", class: 'btn btn-default btn-lg btn-submit btn-primary my-2 '%>
  
<% end %>

</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-9 p-0" style="height:100vh">
    <!--Homepage Nav-->
   
    <img  src="https://via.placeholder.com/728x90?text=728x90+Leaderboard

C/O https://placeholder.com/banner-ads/#46821560_Full_Banner" alt="Generic placeholder image" class="img-responsive" width="600" height="250" style="width: 100%;
  height: auto;">
  <div style="overflow-y: scroll;
  height:480px;">
  <%= render partial: 'ideas/feed', idea: @idea %>
</div>

</div>


    <!-- Right border for users profile-->
    <div class="col-3 border border-muted border-right border-bottom">
      <div>

        <div class="mb-3 text-center">
          <img src="//placehold.it/50" alt="user pic" class="rounded-circle mt-1" style="height:50%; width:50%">
          <p class="text-capitalize m-1"><%= @user.fullname%><br/>
          <small><a href="#">@<%=@user.username%></a></small><br/>
          <% if (@user.id != session[:current_user_id])%>
          <% if check_following(session[:current_user_id], @user.id) == false%>
          <%= button_to "Follow", followings_path(follower_id: session[:current_user_id], followed_id:@user.id),:method => :post, class: "btn btn-lg text-white button-color"%>
          <% else%>
            <%= button_to "Unfollow", unfollow_path(follower_id: session[:current_user_id], followed_id:@user.id),:method => :delete, class: "btn btn-lg text-white button-color"%>
          <% end %>
          <% end %>
          </p>
        </div>
        <div class='d-flex my-4  border-muted ml-4'>
            <p class='px-2  text-center'><span class="font-weight-bold"><%= @user.ideas.count%></span><br><span class="text-muted">Ideas</span></p>
            <p class='px-2 text-center'>
              <span class="font-weight-bold"><%= @user.followings.count%></span>
              <br>
              <span class="text-muted">Followers</span>
            </p>
            <p class='px-2 text-center'>
              <span class="font-weight-bold"><%= @user.followers.count%></span>
              <br>
              <span class="text-muted">Following
            </p>
        </div>
        <p class="text-muted"> FOLLOWED BY</p>
        <% if !@user.followers.empty?%>
        <div class="d-flex mb-3">
          <img src="//placehold.it/50" alt="user pic" class="rounded-circle m-1">
        </div>
        <div class="d-flex mb-3">
          <img src="//placehold.it/50" alt="user pic" class="rounded-circle m-1">
          </p>
        </div>
        <div class="d-flex mb-3">
          <img src="//placehold.it/50" alt="user pic" class="rounded-circle m-1">
          </p>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/sign_in.html.erb
<span class="text-center" style="color:red"><%= alert %></span>
<h1 class="page_title text-center m-2">Sign In</h1>
<div class="container col-md-4 col-md-offset-4">
<% if session[:current_user_id] %>
    <% destroy %>
<% end %>
<div class='mt-4'>
<%= form_tag log_in_path, method: :get do%>
    
    <%= label_tag  "Enter your username"%>
   <%= text_field_tag :username, params[:username], class: 'form-control d-block', autofocus: true,  placeholder: 'Username'%>
   <small id="emailHelp" class="form-text text-muted">
    <%= link_to 'Click here if you\'ve forgotten your username.', recovery_path	, style: "color: white", class: "form-text text-muted"%>
   </small>
    <%= submit_tag "Login", class: 'btn btn-default btn-lg btn-submit btn-primary my-2 '%>
  
<% end %>

<p>  
<small id="emailHelp" class="form-text text-muted">
<%= link_to 'click here if you are a new user', new_user_path%>
</small>
</p>
</div>
</div>